const diagnosticList= [
    "Anaesthesia/Sedation For Radiology",
    "Bone Densitometry Hip",
    "Bone Densitometry Hip & Spine",
    "Bone Densitometry Spine Study",
    "Bone Densitometry Whole body",
    "Echo Screening",
    "Hystero -Salpingography",
    "Ultra Sound For Anomalies (Level-II)",
    "X-Ray Mammography Bilateral",
    "ANKLE BRACHIAL PRESSURE INDEX (ABPI)",
    "BEDSIDE ECHO",
    "DOPPLER PERIPHERAL (CARDIOLOGY)",
    "DUPLICATE CD (CATH LAB)",
    "ECG",
    "ECG for Cardiac Consultation",
    "ECG MAGNET",
    "ECHO (Paediatrics/Neoanatal)",
    "ECHO - DUPLICATE REPORT",
    "ECHO 2D",
    "ECHO Doppler Study",
    "ECHO Fetal Study",
    "ECHO Stress",
    "ECHO Stress (Doubutamine)",
    "ECHO Trans Esophageal (TEE)",
    "Echocardiogram",
    "Fluoroscopy (Cardiac)",
    "FOETAL ECHO",
    "Holter Analysis",
    "Holter Analysis-for 7 days",
    "PACEMAKER CHECKUP/INTRROGATION",
    "PACEMAKER PROGRAMMING (OP)",
    "PACEMAKER TESTING (ECG+CONS.)",
    "Pulmonary Function Tests (PFT)",
    "PULSE GENERATOR",
    "SINGLE/DOUBLE PARAMATER ECHO EVALUATION",
    "TEE",
    "THORACOCENTESIS",
    "TILT Test",
    "TMT",
    "ANKLE(3D )(CT-SCAN)",
    "ANKLE-CT",
    "BOTH HIP(3D)(CT-SCAN)",
    "BOTH SHOULDER (CT )",
    "BRAIN (AXIAL AND CORONAL)(CT-SCAN)",
    "BRAIN WITH PITUITARY FOSSA (CTS)",
    "CAVERNUS SINUS(CT-SCAN)",
    "CD CHARGE (CT-SCAN)",
    "CECT CHEST (CT)",
    "CECT THORAX (CTS)",
    "CERVICAL SPINE (CT-SCAN)",
    "CHEST ROUTINE (CT-SCAN)",
    "CT - HRCT Inspiratory with Expiratory & Prone Scan",
    "CT ANGIO (BOTH LOWER LIMB)",
    "CT ANGIO (BRAIN)",
    "CT ANGIO(ABDOMINAL AORTIC)",
    "CT BRAIN (CT-SCAN)",
    "CT CHEST + UPPER ABDOMEN",
    "CT CHEST + UPPER ABDOMEN WITH CONTRAST",
    "CT CHEST 3D",
    "CT CISTERNOGRAM (CT-SCAN)",
    "CT FACE",
    "CT FACE + NECK PLAIN",
    "CT FACE + NECK WITH CONTRAST",
    "CT FACE WITH CONTRAST",
    "CT NECK WITH CONTRAST",
    "CT NECK WITHOUT CONTRAST",
    "CT SCAN - ABDOMEN SCREENING",
    "CT SCAN - ANGIOGRAPHY ABDOMEN/CHEST",
    "CT SCAN OF PARA NASAL SINUSES- WITH CONTRAST",
    "CT SCAN OF PARA NASAL SINUSES- WITHOUT CONTRAST",
    "CT SCANE HEAD- WITH CONTRAST-WITH CONTRAST INCLUDING CT ANGIOGRAPHY",
    "CT UPPER LIMB ANGIOGRAM",
    "CT UROGRAM (CT-SCAN)",
    "CT-Abdomen -Pelvis/Lower Abdomen with contrast",
    "CT-Abdomen-Dual Phase CT For Liver",
    "CT-Abdomen-Pelvis/Lower Abdomen plain",
    "CT-Angiography - Cerebral",
    "CT-Angiography-Abd Aorta",
    "CT-Angiography-Carotid Artery",
    "CT-Angiography-Localised",
    "CT-Angiography-Peripheral/Extremeties",
    "CT-Angiography-Pulmonary",
    "CT-Angiography-Renal Artery",
    "CT-Chest & Whole Abdomen & Pelvis With Contrast",
    "CT-Chest - HRCT",
    "CT-CHEST - HRCT [COVID PATIENT]",
    "CT-CHEST - HRCT [NON COVID PATIENT]",
    "CT-Chest plain / CT Thorax",
    "CT-Chest With Contrast",
    "CT-Contrast 100 ML",
    "CT-Contrast 50 ML",
    "CT-Guided Trucut Biopsy (Consumable & Contrast Extra)",
    "Ct-guided Trucut Biopsy with consumable",
    "CT-head - Iam/Temporal Bone",
    "CT-head - Iam/Temporal Bone With 3D",
    "CT-head -Cisternogram",
    "CT-Head Contrast",
    "CT-head Pitutary- Sella Contrast",
    "CT-Head Plain",
    "CT-head-Pituitary-Sella",
    "CT-Joints Contrast",
    "CT-Joints Plain",
    "CT-Joints With 3D",
    "CT-KUB (Contrast)",
    "CT-KUB (Plain)",
    "CT-Maxillo-Facial Trauma 3D",
    "CT-Neck & Chest With Contrast",
    "CT-Neck Plain",
    "CT-Neck, Chest, whole Abdomen & Pelvis With Contrast",
    "CT-Neck/Pharynx/Larynx (Contrast)",
    "CT-neuro (Repeat- Plain)- within 7 days",
    "CT-Orbits (Plain)",
    "CT-Orbits with Contrast",
    "CT-PNS with Contrast",
    "CT-PNS-Plain",
    "CT-Procedures-Diagnostic for fluid Aspiration (Consumable Extra)",
    "CT-Spine-Cervical",
    "CT-Spine-Lumbar/Dorsal Spine",
    "CT-Spine-Lumbosacral Spine (Plain)",
    "CT-Spine-Myelogram",
    "CT-Spine-With Contrast",
    "CT-Upper Abdomen Plain",
    "CT-Upper Abdomen With Contrast",
    "CT-Urogram / urography",
    "CT-Whole Abdomen Plain",
    "CT-Whole Abdomen With Contrast",
    "CV JUNCTION (CT-ANGIO)",
    "DORSO-LUMBER SPINE (3D)(CT-SCAN)",
    "ESOPHAGUS(CT-SCAN)",
    "FACE(3D)(CT-SCAN)",
    "FEMUAR CT-SCAN",
    "FEMUR (3D)(CTS)",
    "FINGER(CT-SCAN)",
    "FOOT(CT-SCAN)",
    "FORE ARM(CT-SCAN)",
    "HAND(3D)(CT-SCAN)",
    "HRCT OF LUNG/CHEST(CT-SCAN)",
    "HRCT THORAX",
    "HRCT-TEMPORAL BONE(CT-SCAN)",
    "HUEMURS(CTS)",
    "K.U.B.(CT-SCAN) PLAIN",
    "KNEE JOINT(3D)(CTS)",
    "L-S SPINE CT",
    "LEG(3D)(CTS)",
    "LOWER ABDOMEN(CT-SCAN) CONTRAST",
    "LOWER ABDOMEN(CT-SCAN) PLAIN",
    "LUMBO-SACRAL(3D)(CT-SCAN)",
    "MANDIBLE (3D) (CT-SCAN)",
    "MASTOIDROUTINE(CT-SCAN)",
    "MOSTOID(CT-SCAN)",
    "MYELOGRAM (CT-SCAN)",
    "NASOPHARYNX (CTS)",
    "NECK WITH CONTRAST (CT-SCAN)",
    "ORAL CAVITY (CT-SCAN)",
    "ORBIT (CTS)",
    "PELVIS (3D)(CT-SCAN)",
    "PELVIS WITH BOTH HIP (3D) (CT-SCAN)",
    "PITUITARY FOSSA (CTS)",
    "PNS AXIAL AND CORONAL (CT-SCAN)",
    "PNS CORONAL (CT-SCAN) PLAIN",
    "PNS CORONAL (CT-SCAN)CONTRAST",
    "PNS ROUTINE (CTS)",
    "PNS WITHOUT CONTRAST(CT-SCAN)",
    "POLY TRAUMA PROFILE -1 - NCCT BRAIN + WHOLE SPINE + NCCT CHEST + WHOLE ABDOMEN + X-RAY PELVIS(AP VIEW)",
    "SHOULDER JOINT (3D)(CT-SCAN)",
    "SWELLING OF BODY PART (CT-SCAN)",
    "TEMPORAL BONE (CT-SCAN)",
    "THIGHS(CTS)",
    "THORACIC SPINE (3D) (CT-SCAN)",
    "TRAUMA PROFILE -1 - NCCT BRAIN + C-SPINE",
    "TRAUMA PROFILE -2 - NCCT BRAIN + C-SPINE + FACE",
    "TRAUMA PROFILE -3 - NCCT CHEST + WHOLE ABDOMEN",
    "TRAUMA PROFILE -4 - NCCT BRAIN + C-SPINE + FACE + CHEST + WHOLE ABDOMEN",
    "TRAUMA PROFILE -5 - NCCT WHOLE SPINE",
    "TRIPLE PHASE WHOLE ABDOMEN",
    "UPPER ABDOMEN(CT-SCAN) CONTRAST",
    "UPPER ABDOMEN(CT-SCAN)PLAIN",
    "WHOLE ABDOMEN(CT-SCAN) PLAIN",
    "WHOLE ABDOMEN(CT-SCAN)CONTRAST",
    "WRIST(3D)(CT-SCAN)",
    "BEDSIDE NCS ALL FOUR LIMBS",
    "Blink Reflex",
    "Brachial Plexus Study",
    "Braintstem Auditary Evoked Response",
    "EEG (AWAKE + SLEEP)",
    "EEG (SLEEP / SLEEP DEPRIVED)",
    "EEG Bed Side",
    "EEG Routine",
    "Emergency EEG",
    "EMG ALL FOUR LIMBS",
    "EMG ALL FOUR LIMBS INCLUDING PARASPINAL & TOUNGE MUSCLES",
    "EMG more than two Limbs*",
    "EMG One Limb*",
    "EMG Two Limbs*",
    "NCS & EMG ALL FOUR LIMBS INCLUDING PARASPINAL AND TONGUE MUSCLES",
    "NCS & EMG LOWER LIMBS",
    "NCS & EMG UPPER LIMBS",
    "NCS & EMG UPPER LIMBS + BRACHIAL PLEXUS STUDY",
    "NCS & EMG ALL FOUR LIMBS",
    "NCS ALL FOUR LIMBS",
    "NCS FACIAL NERVES",
    "NCS LOWER LIMBS",
    "NCS LOWER LIMBS + LUMBAR PLEXUS STUDY",
    "NCS UPPER LIMBS",
    "NCS UPPER LIMBS + BRACHIAL PLEXUS STUDY",
    "NCV & Emg All Six/ Nine Limbs*",
    "NCV ALL FOUR LIMBS + REPETITIVE NERVE STIMULATION TEST (RNST)",
    "NCV Motor & Sensory more than two Limbs",
    "NCV Motor & Sensory One Limb",
    "NCV Motor & Sensory Two Limb",
    "Repetitive Nerve Stimulation",
    "REPETITIVE NERVE STIMULATION TEST (RNST)",
    "Short Term VEEG up to 4 hours",
    "Sleep Study Overnight",
    "Sleep Study titration",
    "Somato Sensory Evoked Potential",
    "Split Night Study",
    "VEEG ( 24 hours)",
    "VEEG ( Overnight/12 hours)",
    "VEEG every additional hour",
    "VEP- visually evoked potential",
    "Video EEG less than 1 hour",
    "Visual Evoked Potential",
    "Audiometry Test",
    "Bronchial artery embolisation (Simple) consumable",
    "Bronchial artery embolisation( Complex) consumable",
    "Check Cholangiogram",
    "Check Nephrostogram",
    "Chemo- embolisation (Complex) consumable extra",
    "Chemo- embolisation (Simple) consumable extra",
    "CT GUIDED Aspiration( Diagnostic)",
    "CT GUIDED Aspiration( Therapeutic)",
    "CT GUIDED BIOPSY (With consumables and contrast)",
    "CT GUIDED BIOPSY (With consumables and without con",
    "CT GUIDED BIOPSY (Without consumables)",
    "CT GUIDED Pigtail complex( consumables extra)",
    "CT GUIDED Pigtail simple ( consumables extra)",
    "CT-Guided FNAC",
    "CT/MR myelogram/cisternogram/arthrogram (includes",
    "Fluoro Guided sclerotherapy (complex) consumable e",
    "Fluoro Guided sclerotherapy (simple) consumable ex",
    "Intraarticular injections Fluoro guided",
    "Intraarticular injections US guided",
    "INTRAVASCULAR ULTRASOUND (IVUS)",
    "PCN (single) with consumable",
    "Peripheral DSA consumable extra",
    "Peripheral/Body aneurym embolisation( Simple) cons",
    "Peripheral/Body aneurysm embolisation (Complex) co",
    "Peripheral/Body AVM embolisation Complex",
    "Peripheral/Body AVM embolisation( Simple) consumab",
    "Peripheral/Visceral Check DSA",
    "PTBD (single) with consumable",
    "PTBD (single) without consumable",
    "Re-positioning PCN without consumable",
    "Re-positioning PTBD without consumable",
    "US Guided Biopsy (With Consumables Automatic Gun)",
    "US Guided Diagnostic Aspiration (Consumable Extra)",
    "US Guided FNAC",
    "US Guided Prostate Biopsy (Without Consumable)",
    "US GUIDED Therapeutic Aspiration",
    "USG GUIDED BIOPSY with consumables( semiautomatic",
    "USG GUIDED Pigtail catheter Placement (complex) wi",
    "USG GUIDED Pigtail catheter Placement (simple) wit",
    "USG GUIDED Sclerotherapy (complex) without consuma",
    "USG GUIDED Sclerotherapy (simple) without consumab",
    "Visceral Aneurysm/ peripheral coiling complex cons",
    "Visceral Aneurysm/ peripheral coiling( simple) con",
    "Visceral DSA consumable extra",
    "X-Ray Mammography Unilateral",
    "MR Angio Brain (Plain)",
    "MR Angio Brain - With Contrast",
    "MR Angiogram - With Contrast",
    "MR ANGIOGRAPHY",
    "MR MYELOGRAM",
    "MR Spectroscopy (Plain)",
    "MR Spectroscopy - With Contrast",
    "MR VENOGRAM",
    "MR.UROGRAPHY",
    "MRA ANGIO UPPER LIMB",
    "MRCP (Plain)",
    "MRCP - With Contrast",
    "MRI BRAIN WITH SCREENING BRACHIAL PLEXUS",
    "MRI BRAIN SCREENING",
    "MRI HIP (B/L SCREENING)",
    "MRI LS SPINE WITH SCREENING S.I. JOINT",
    "MRI (CD charges)/(Extra Film)",
    "MRI ABDOMEN (LIVER DYNAMIC)",
    "MRI ABDOMEN WITH CONTRAST",
    "MRI ABDOMEN WITHOUT CONTRAST",
    "MRI ABDOMINAL ANGIO",
    "MRI ANAESTHESIA CHARGES",
    "MRI ANGIO LOWER LIMB",
    "MRI ANKEL",
    "MRI Ankle single joint - With contrast",
    "MRI Ankle Single joint - Without contrast",
    "MRI ANKLE WITH CONTRAST",
    "MRI BOTH HIP",
    "MRI BOTH KNEE",
    "MRI BOTH KNEE SCREENING",
    "MRI BOTH SOULDER",
    "MRI Brachial Plexus (Plain)",
    "MRI Brachial Plexus - With Contrast",
    "MRI BRAIN + MRA + MRV PLAIN",
    "MRI BRAIN + MRA + MRV WITH CONTRAST",
    "MRI BRAIN + NECK ANGIO (FULL STUDY)",
    "MRI BRAIN + NECK ANGIO (FULL STUDY) WITH CONTRAST",
    "MRI BRAIN + PERFUSION",
    "MRI BRAIN + PERFUSION WITH CONTRAST",
    "MRI BRAIN + VENOGRAM",
    "MRI BRAIN + VENOGRAM WITH CONTRAST",
    "MRI BRAIN EPILEPSY PROTOCOL",
    "MRI Brain Plain",
    "MRI Brain Plain - With Contrast",
    "MRI Brain Posterior Fossa (Pituitary) (Plain)",
    "MRI BRAIN SPECTROPSCOPY",
    "MRI BRAIN STROKE PROTOCOL(NON-CONTRAST)",
    "MRI BRAIN STROKE PROTOCOL(WITH CONTRAST)",
    "MRI BRAIN VENOGRAPHY MRV",
    "MRI BRAIN WITH CSF FLOW STUDY",
    "MRI BRAIN WITH DTI",
    "MRI Brain With Functional (Plain)",
    "MRI Brain With Functional - With Contrast",
    "MRI Brain With Spectroscopy (Plain)",
    "MRI Brain With Spectroscopy - With Contrast",
    "MRI Brain(Pituitary) - With Contrast",
    "MRI BRAIN+DTI WITH NAVIGATION PROTOCOL (NON-CONTRAST)",
    "MRI BRAIN+DTI WITH NAVIGATION PROTOCOL (WITH CONTRAST)",
    "MRI BRAIN+MRA",
    "MRI BRAIN+MRA+NECK ANGIO",
    "MRI BRAIN+ORBIT WITH CONTRAST",
    "MRI BRAIN+ORBIT( PLAIN)",
    "MRI BRAIN+ORBIT+PNS",
    "MRI BRAIN+ORBIT+PNS WITH CONTRAST",
    "MRI BRAIN+PNS WITH CONTRAST",
    "MRI BRAIN+PNS( PLAIN)",
    "MRI BRAIN+SCREENING C- SPINE",
    "MRI BREAST",
    "MRI BREAST WITH CONTRAST",
    "MRI C- SPINE WITH SCREENING BRACHIAL PLEXUS",
    "MRI Cardiac (Plain)",
    "MRI Cardiac - With Contrast",
    "MRI CERVICAL SPINE WITH SCEENING BRAIN",
    "MRI Chest/Thorax (Plain)",
    "MRI Chest/Thorax- With Contrast",
    "MRI CISTERNOGRAPHY",
    "MRI CISTERNOGRAPHY WITH CONTRAST",
    "MRI CONTRAST CHARGE",
    "MRI CP ANGLE",
    "MRI CSF FLOW STUDY",
    "MRI CV JUNCTION",
    "MRI D- L SPINE WITH SCREENING PELVIS",
    "MRI D- L SPINE WITH SCREENING S.I. JOINT",
    "MRI DTI SEQ.",
    "MRI ELBOW LEFT",
    "MRI ELBOW RIGHT",
    "MRI ELBOW WITH CONTRAST",
    "MRI EXTREMITIES - WITH CONTRAST",
    "MRI EXTREMITIES - WITHOUT CONTRAST",
    "MRI FACE",
    "MRI FACE + NECK WITH CONTRAST",
    "MRI FACE PLAIN",
    "MRI FACE WITH CONTRAST",
    "MRI FACE+NECK CONTRAST",
    "MRI FETAL",
    "MRI FINGER",
    "MRI FOOT",
    "MRI FOOT WITH CONTRAST",
    "MRI FULL BODY DWIBS",
    "MRI FUSTLOGRAM PLAIN",
    "MRI FUSTLOGRAM WITH CONTRAST",
    "MRI HAND",
    "MRI HAND WITH CONTRAST",
    "MRI JOINT S.I",
    "MRI Knee (Plain)",
    "MRI Knee - With Contrast",
    "MRI KNEE BOTH JOINTS - WITHOUT CONTRAST",
    "MRI KNEE SCREENING (SINGLE)",
    "MRI L-S SPINE WITH SCREENING PELVIS",
    "MRI L.S.PLEXUS",
    "MRI LEG+MRA CONTRAST",
    "MRI LOCAL REGION",
    "MRI LOCAL REGION CONTRAST",
    "MRI Lower Abdomen (Plain)",
    "MRI Lower Abdomen - With Contrast",
    "MRI Lumbar/ Lumbo-Sacral Spine",
    "MRI Lumbar/ Lumbo-Sacral Spine - With Contrast",
    "MRI Nasopharynx/Larynx (Plain)",
    "MRI Nasopharynx/Larynx - With Contrast",
    "MRI NECK",
    "MRI NECK + BRAIN ANGIO (SCREENING) WITH CONTRAST",
    "MRI NECK + BRAIN ANGIO SCREENING",
    "MRI Neck / Thyroid - With Contrast",
    "MRI NECK ANGIO",
    "MRI NECK CONTRAST",
    "MRI Orbits (Plain)",
    "MRI Orbits - With Contrast",
    "MRI PELVIS CONTRAST",
    "MRI PELVIS PLAIN",
    "MRI Peripheral (Plain)",
    "MRI Peripheral - With Contrast",
    "MRI PNS",
    "MRI PNS WITH CONTRAST",
    "MRI PROSTATE WITH CONTRAST",
    "MRI Renal Angio (Plain)",
    "MRI Renal Angio - With Contrast",
    "MRI RT LOWER LIMB VENOGRAM",
    "MRI SCREENING HIP",
    "MRI SCREENING S.I JOINT",
    "MRI SHOULDER LEFT",
    "MRI SHOULDER RIGHT",
    "MRI Single Joint (Plain)",
    "MRI Single Joint - With Contrast",
    "MRI Single Part - Musculo Skeletal (Plain)",
    "MRI Single Part - Musculo Skeletal - With Contrast",
    "MRI SPECTRO + PERFUSION + DTI",
    "MRI Spine Cervical (Plain)",
    "MRI Spine Cervical - With Contrast",
    "MRI Spine Dorsal (Plain)",
    "MRI Spine Dorsal - With Contrast",
    "MRI Spine Dorsolumbar (Plain)",
    "MRI Spine Dorsolumbar - With Contrast",
    "MRI Spine Lumbar (Plain)",
    "MRI Spine Lumbar - With Contrast",
    "MRI Spine Screening - Without Contrast",
    "MRI T.M JOINT",
    "MRI THIGH /LEG LEFT",
    "MRI THIGH /LEG RIGHT",
    "MRI THIGH/LEG WITH CONTRAST",
    "MRI TONGUE",
    "MRI TOTAL KIDNEY VOLUME",
    "MRI Upper Abdomen (Plain)",
    "MRI Upper Abdomen - With Contrast",
    "MRI Whole Abdomen + Pelvis (Plain)",
    "MRI Whole Abdomen + Pelvis (With Contrast)",
    "MRI WHOLE SPINE SCREENING (PLAIN)",
    "MRI WHOLE SPINE SCREENING - WITH CONTRAST",
    "MRI WRIST",
    "MRI WRIST with Contrast",
    "MRI FACE + NECK PLAIN",
    "ONLY SINGLE PART SCREENING",
    "CT (CD charges)/(Extra Film)",
    "Emergency Charges - Radiology (At Night)",
    "Ultra Sound (Extra Film)",
    "X-Ray (Extra Film)",
    "Uroflowmetry",
    "ICU POCUS",
    "Reusable Gun",
    "Sclerotherapy under DSA and USG(Consumables Extra)",
    "Small Parts USG- Scrotum, Thyroid, Parathyroid etc",
    "Ultra Sound - Cranium",
    "Ultra Sound - Fetal Echo",
    "Ultra Sound - Inguinal & Scrotum",
    "Ultra Sound - Inguinal Region",
    "Ultra Sound - Local Region",
    "Ultra Sound Brain",
    "Ultra Sound Breast Bilateral",
    "Ultra Sound Breast Unilateral",
    "Ultra Sound Carotid Doppler",
    "Ultra Sound Chest",
    "Ultra Sound Color Doppler - Both Limbs - Arterial",
    "Ultra Sound Color Doppler - Both Limbs - Venous",
    "Ultra Sound Color Doppler - Local Swelling",
    "Ultra Sound Color Doppler Peripheral Venous One Limb",
    "Ultra Sound Color Doppler Renal",
    "Ultra Sound Color Doppler Vascular",
    "Ultra Sound Color Doppler- Abdominal Aorta",
    "Ultra Sound Color Doppler- Carotids",
    "Ultra Sound Color Doppler- Obstetrics",
    "Ultra Sound Color Doppler- Peripheral Arterial One Limb",
    "Ultra Sound Color Doppler-Penile Doppler",
    "Ultra Sound Color Doppler-Peripheral Venous One Limb",
    "Ultra Sound Color Doppler-Splenoportal Axis",
    "Ultra Sound Extremity/Joint",
    "Ultra Sound Fetal Growth Monitoring",
    "Ultra Sound Fetal wellbeing",
    "Ultra Sound Follicle Monitoring (6 days)",
    "Ultra Sound for MTP",
    "Ultra Sound Home service",
    "Ultra Sound Knee - Both",
    "Ultra Sound Knee - Left",
    "Ultra Sound Knee - Right",
    "Ultra Sound KUB",
    "Ultra Sound KUB & PVR",
    "Ultra Sound KUB & Scrotum",
    "Ultra Sound Lower Abdomen/Pelvis",
    "Ultra Sound Neck",
    "Ultra Sound Obstetrics (7-11 WEEKS)",
    "Ultra Sound Obstetrics (NTNB Scan)-Level-I",
    "Ultra Sound Orbits",
    "Ultra Sound Pelvis & Scrotum",
    "Ultra Sound Pelvis Doppler",
    "Ultra Sound Pelvis-Transabdominal",
    "Ultra Sound Pelvis-Transvaginal",
    "Ultra Sound Pregnancy With Color Doppler",
    "Ultra Sound Renal Doppler",
    "Ultra Sound Scrotal Doppler",
    "Ultra Sound Scrotum",
    "Ultra Sound Thyroid",
    "Ultra Sound Transrectal",
    "Ultra Sound Upper Abdomen",
    "Ultra Sound Whole Abdomen",
    "Ultra Sound Whole Abdomen with Pelvis (PVR)",
    "Ultrasound Screening",
    "ULTRASOUND SCREENING IPD",
    "US Abdomen With TVS",
    "Us Guidance For D&C",
    "US Guided Ascitic Fluid Aspiration (Diagnostic)",
    "US Guided Biopsy (Consumable Extra)",
    "US Guided Biopsy (With Semi-automatic Gun)",
    "US Guided Prostate Biopsy (With Consumable)",
    "USG Color Doppler - B/L Limbs- Arterial &Venous",
    "USG Color Doppler - Single Limb- Arterial &Venous",
    "USG FOLLICULAR MONITORING",
    "USG FOR INTRA-OPERATIVE",
    "USG Guided Ascitic Fluid Aspiration (Therapeutic)",
    "USG GUIDED BLOCK",
    "USG Guided Sclerotherapy",
    "Extremities, bones & Joints AP & Lateral views (Two films)",
    "Intravenous Pyelography (IVP)",
    "X-Ray Abdomen - Decubitus",
    "X-Ray Abdomen - Erect",
    "X-Ray Abdomen - Other",
    "X-Ray Abdomen - Supine",
    "X-RAY ABDOMEN AND PELVIS FOR KUB",
    "X-Ray Abdomen-Ap",
    "X-Ray Ankle Joint Ap & Lat",
    "X-Ray Arm Ap & Lat",
    "X-Ray Arm Ap Only",
    "X-Ray Barium Enema (Dc)",
    "X-Ray Barium Meal",
    "X-Ray Barium Meal Follow Through",
    "X-Ray Barium Swallow",
    "X-Ray Both Ankle Joint - Lateral",
    "X-RAY BOTH CAL CANIUM AP/LAT",
    "X-Ray Both Knee Joints Ap & Lat",
    "X-Ray Calcaneum -Ap & Axial",
    "X-Ray Chest -Ap",
    "X-Ray Chest -Decubitus (Right/Left)",
    "X-Ray Chest -Other - One View",
    "X-Ray Chest -Pa",
    "X-Ray Chest Lateral (one film)",
    "X-Ray Chest Lateral (Right/Left)",
    "X-Ray Chest-Oblique (For Ribs)",
    "X-Ray Clavicle / Acromio -Clav Jt (Right/Left)",
    "X-Ray Coccyx Ap & Lat",
    "X-Ray Colostomy Study",
    "X-Ray Cystography",
    "X-Ray Digits-Ap &Lat",
    "X-Ray Elbow Joint -Ap & Lat",
    "X-Ray Femur Ap Only",
    "X-Ray Femur Lat Only",
    "X-Ray Femur-Ap & Lat",
    "X-Ray Fistulography",
    "X-Ray Foot - Any Other 1 View",
    "X-Ray Foot-Ap & Lat",
    "X-Ray For Tm Joints -Open & Close Mouth Both Side",
    "X-Ray For Tm Joints -Open & Close Mouth One Side",
    "X-Ray Forearm -Ap & Lat",
    "X-Ray Forearm Ap",
    "X-Ray Gastrografin Study",
    "X-Ray Hand Ap",
    "X-Ray Hands -Ap & Lat",
    "X-Ray Hands Ap & Obl",
    "X-Ray Hip Joint -Ap & Lat",
    "X-Ray Hip joint Ap",
    "X-Ray Hip joint Lateral",
    "X-Ray Humerus -Ap & Lat",
    "X-Ray Invertogram",
    "X-Ray IVP (Non-Ionic Contrast)",
    "X-Ray IVP + MCU Film",
    "X-Ray Knee Joint - Ap & Lat",
    "X-Ray Knee Joints Ap Only",
    "X-Ray Knee Joints Lat Only",
    "X-Ray Kub",
    "X-Ray Leg - Ap & Lat",
    "X-Ray Leg Lat Only",
    "X-ray Mastoids (Both Side)",
    "X-Ray Mastoids (One Side)",
    "X-Ray Micturating Cystography",
    "X-Ray Nasal Bones",
    "X-Ray Neck - For Soft Tissues -Lat",
    "X-Ray Nephrostogram (Non Ionic Contrast)",
    "X-Ray Pelvis -Ap",
    "X-Ray Pelvis-Ap Incl Both Hip Joints",
    "X-Ray Pns-Waters View",
    "X-Ray Retrograde Urethrography",
    "X-Ray RGU & MCU",
    "X-Ray Sacro-Iliac Joints- Obl",
    "X-Ray Sacro-Iliac Joints-ap",
    "X-Ray Scapula Ap & Lat",
    "X-Ray Sella (Pituitary Fossa)",
    "X-Ray Shoulder Joint-Ap",
    "X-Ray Shoulder Joint-Ap & Axial",
    "X-Ray Sialogram Bilateral",
    "X-Ray Sialogram Unilateral",
    "X-Ray Single Film",
    "X-Ray Skull -Any 2 Views",
    "X-Ray Skull For Styloid Process",
    "X-Ray Skull Lat",
    "X-Ray Skull Oblique",
    "X-Ray Skull-Ap & Lat",
    "X-Ray Special Views For Orbits",
    "X-Ray Special Views- For Mandible Ap & Oblique",
    "X-Ray Special Views-For Iam",
    "X-Ray Special Views-For Jugular Foramen",
    "X-Ray Special Views-For Mastoids",
    "X-Ray Spine Dorsal Ap",
    "X-Ray Spine-Cervical Ap",
    "X-Ray Spine-Cervical Ap & Lat",
    "X-Ray Spine-Cervical Both Obl",
    "X-Ray Spine-Cervical Flex & Ext",
    "X-Ray Spine-Cervical Lat",
    "X-Ray Spine-Cervico-Thoracic Ap & Lat",
    "X-Ray Spine-Cv Junction 2 Views",
    "X-Ray Spine-Dorsal Ap & Lat",
    "X-Ray Spine-Lumbar -Both Obl",
    "X-Ray Spine-Lumbar Ap",
    "X-Ray Spine-Lumbar Ap & Lat",
    "X-Ray Spine-Lumbar Lat",
    "X-Ray Spine-Lumbo-Sacral Ap & Lat",
    "X-Ray Spine-Lumbo-Sacral Flex & Ext",
    "X-Ray Spine-Thoracic Ap & Lat",
    "X-Ray Spine-Thoraco-Lumbar Ap & Lat",
    "X-Ray Sterno-Clavicular Joint-Both Obliques",
    "X-Ray Sternum Ap & Lat",
    "X-Ray Sternum Lat",
    "X-Ray Sternum Lat & Obl",
    "X-Ray Styloid Process",
    "X-Ray T- Tube Cholangiogram",
    "X-Ray Thigh Ap & Lat",
    "X-Ray Thigh Ap Only",
    "X-Ray Wirst Joint -Any 3 Views",
    "X-Ray Wrist Joint- 1 View",
    "X-Ray Wrist Joint-Any 2 Views",
    "X-Ray Wrist Joint-Ap & Lat"
  ]

  export default diagnosticList;